### ISSUE TITLE
Allow nested hashes to be passed in on initialisation

### ISSUE THREAD

**Issue by cobalamin** [airbnb/polyglot.js#10]
I defined my translations like this:

```
nav:
  presentations: "Presentations"
  users: "Users"
  devices: "Devices"
```

and expected `polyglot.t("nav.presentations")` to work. It did not, but told me the translation was missing. After a little investigation, I found out that defining it like this instead:

```
nav.presentations: "Presentations"
nav.users: "Users"
nav.devices: "Devices"
```

fixes the "issue". I was somewhat disappointed to find out that I have to pollute up my translation files like this if I want to use Polyglot. Is it possible to add this feature?
